### ISSUE TITLE
--restart flag support process kill with custom signal?

### ISSUE THREAD

**Issue by TSMMark** [filewatcher/filewatcher#106]
I'm running into an issue using `filewatcher` to run and restart because I require the child process to perform some cleanup before being force killed with KILL 9 signal.

With my limited understanding of the intricacies of this gem, it seems like it should be pretty straight forward to support any value instead of `9` here:

https://github.com/filewatcher/filewatcher/blob/575e1d5a0dad2f079684ec97e4b084ea9f1e71ab/bin/filewatcher#L56

I'd be happy to implement this feature. Please let me know if I'm missing anything and if you'd accept a PR

**Comment by AlexWayfer** [comment]
@TSMMark hello! Thank you for report. Sorry for delay.

I have not completely understood your problem, to be honest. Especially, what is "child process"? Filewatcher or something else? And what is "parent process" which have to exists alongside "child" one?

I'm able to review any your request with justification and tests.

**Comment by TSMMark** [comment]
Hi @AlexWayfer 

Yes, here in the restart method we always use a kill 9

https://github.com/filewatcher/filewatcher/blob/575e1d5a0dad2f079684ec97e4b084ea9f1e71ab/bin/filewatcher#L53-L62

I don't remember why I needed this functionality tbh, but optionally couldn't a different kill number be sent?

**Comment by AlexWayfer** [comment]
> I don't remember why I needed this functionality tbh, but optionally couldn't a different kill number be sent?

So, you don't need for this anymore? I agree that `KILL` is not good, although guaranteed, and I've created #117 — you can test if you want.
