### ISSUE TITLE
Sync to database example

### ISSUE THREAD

**Issue by ridhwaans** [filewatcher/filewatcher#186]
how do you map the directory being watched recursively to a database? every file minus subdirectories is a db record.   
how do you implement indexing to tell the database the list of filepaths and filenames that were created, removed, moved or renamed?

**Comment by AlexWayfer** [comment]
Sorry, I don't understand what do you mean about "database". In-memory Hash-like variable? Filewatcher has no support of databases like RDBMS or key-value or even in-file.
