### ISSUE TITLE
How do I know which directory has changed when there is a change

### ISSUE THREAD

**Issue by liwyan** [filewatcher/filewatcher#214]
I am listening to several directories at the same time. How do I know which directory has changed when there is a change?
The Initialize looks something like this
`Filewatcher.new(['/tmp/test/1', '/tmp/test/2', '/tmp/fisrt']).watch do |changes|
end`

**Comment by AlexWayfer** [comment]
Have you get it?

As you can see in the README, `changes` kind of Hash, there are code like `changes.each do |filename, event|`, so keys of this Hash are filenames (paths), and if you want to get only a directory — you can call something like [`File.dirname`](https://ruby-doc.org/core-3.1.2/File.html#method-c-dirname).
