### ISSUE TITLE
Stable release soon?

### ISSUE THREAD

**Issue by DannyBen** [filewatcher/filewatcher#218]
This ticket was originally about the README instructions that are different than the actual code, but then I saw #202.

When is the beta going to make it to a stable release? It is in beta for 2 years, and the last stable is 4 years ago - which is quite discouraging....

**Comment by AlexWayfer** [comment]
I've got it. Thank you for notification. I'll try to release it soon.

For understanding: the whole ecosystem and concept of Filewatcher has changed, now it's an organization with plugins, like https://github.com/filewatcher/filewatcher-cli/issues/19 and https://github.com/filewatcher/filewatcher-spinner/issues/48

Also I want to have almost each gem (plugin) successfully been tested in CI, including Windows, macOS, JRuby, Truffle, etc., as it was defined originally. And I'll be honest it's not easy.

I respect your attention and will try to do my best.

**Comment by AlexWayfer** [comment]
The whole ecosystem has been released. :tada:
