### ISSUE TITLE
Filewatcher not found in Ruby 3.2.2

### ISSUE THREAD

**Issue by daBee** [filewatcher/filewatcher#249]
I just ran into this moving into `3.2.2`:

```
rbenv: filewatcher: command not found

The `filewatcher' command exists in these Ruby versions:
  2.7.4
  3.1.2
```

**Comment by daBee** [comment]
Any update?

**Comment by AlexWayfer** [comment]
@daBee sorry, I've missed this.

I don't understand what do you mean.

Maybe you've missed the latest large update?

https://github.com/filewatcher/filewatcher/releases/tag/v2.0.0

[CLI](https://github.com/filewatcher/filewatcher-cli) is now a plugin for Filewatcher. As well as other features, not required by default (all of us).

Please, check the README.

**Comment by daBee** [comment]
I just checked:

```
>>> 14:55:01 user3@myworkstation ~ ➜ gem info filewatcher

*** LOCAL GEMS ***

filewatcher (2.1.0)
    Authors: Thomas Flemming, Alexander Popov
    Homepage: http://github.com/filewatcher/filewatcher
    License: MIT
    Installed at: /Users/user3/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0

    Lightweight filewatcher.
>>> 14:55:09 user3@myworkstation ~ ➜ kk
rbenv: filewatcher: command not found

The `filewatcher' command exists in these Ruby versions:
  2.7.4
  3.1.2
```

**Comment by AlexWayfer** [comment]
> I just checked:
> 
> ```
> >>> 14:55:01 user3@myworkstation ~ ➜ gem info filewatcher
> 
> *** LOCAL GEMS ***
> 
> filewatcher (2.1.0)
>     Authors: Thomas Flemming, Alexander Popov
>     Homepage: http://github.com/filewatcher/filewatcher
>     License: MIT
>     Installed at: /Users/user3/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
> 
>     Lightweight filewatcher.
> >>> 14:55:09 user3@myworkstation ~ ➜ kk
> rbenv: filewatcher: command not found
> 
> The `filewatcher' command exists in these Ruby versions:
>   2.7.4
>   3.1.2
> ```

You've just checked what? Do you understand the information about separate `filewatcher-cli` gem?

CHECK THE README PLEASE.

**Comment by daBee** [comment]
There was nothing in the README about this.  I've been using `filewatcher` for over ten years, never had to install this alternate `gem`.  But it works now that it's installed.

**Comment by AlexWayfer** [comment]
> There was nothing in the README about this.

https://github.com/filewatcher/filewatcher/blob/ee730dc/README.md#plugins




> I've been using `filewatcher` for over ten years, never had to install this alternate `gem`. But it works now that it's installed.

You've upgraded this gem to a new major version, 2.0. [SemVer](https://semver.org/) tells us that any major update can bring any breaking changes. And you should check the changelog, patch notes, as I referred above.

Be careful with version locks.

**Comment by daBee** [comment]
OK, this is what it says about `filewatcher-cli`:
```
Official plugins:

[CLI](https://github.com/filewatcher/filewatcher-cli)
```

That's it.  It also says this:
```
If you have questions, problems or suggestions about plugins system — please, don't hesitate to [create a new issue](https://github.com/filewatcher/filewatcher/issues/new).
```

**Comment by AlexWayfer** [comment]
> It also says this:

I'm not against issues. I just don't understand "command not found" without details. As you see, we've figured out the reasons.



> It was working up until recently. I'm on `2.1.0` and `2.0` came out November last year.

I don't know what is "recently" for you. 2.0 has breaking changes, as I wrote. You can lock versions like `~> 2.0`. Both, 2.0 and 2.1, have been released more than half-year ago. "Recently"? Like a few days ago or what?

**Comment by daBee** [comment]
Recently: last week.

**Comment by AlexWayfer** [comment]
> Recently: last week.

As you can see, there were no updates for months. It's an issue with your versions locking.

https://rubygems.org/gems/filewatcher

![image](https://github.com/filewatcher/filewatcher/assets/6510020/a89f0f9c-effb-408c-81e0-1ac84bcc73e4)

**Comment by daBee** [comment]
Strange as there are no dependencies whatsoever.  I assumed it has something to do with `3.2.2` and something internal with `filewatcher`.  I've not had the cli gem before.

**Comment by AlexWayfer** [comment]
> Strange as there are no dependencies whatsoever.

The default policy was to exclude CLI from the main gem.
Not required at all.
As a breaking change for 2.0.



> I assumed it has something to do with `3.2.2` and something internal with `filewatcher`.

No.




> I've not had the cli gem before.

It didn't exist before Filewatcher v2. Before it was bundled into, after it's a separate gem.

**Comment by daBee** [comment]
Good to know.  Cheers
