### ISSUE TITLE
Detect File Read

### ISSUE THREAD

**Issue by lukewakeford** [filewatcher/filewatcher#55]
Hey, I'm looking for a way to monitor file access not modification.

Is there a way to monitor when a file is being read?

Thanks.

**Comment by AlexWayfer** [comment]
I think we can with `File.atime` in snapshots (and additional option).

**Comment by AlexWayfer** [comment]
@lukewakeford Do you want to check this functionality in separate branch (#62) before merging?

**Comment by lukewakeford** [comment]
Sure!

**Comment by AlexWayfer** [comment]
> The NTFS file system delays updates to the last access time for a file by up to 1 hour after the last access.

[Source](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290(v=vs.85).aspx).

Oh my god! 😱 

This feature will not work for Windows.

```ruby
File.atime('env') #=> 2017-06-24 23:21:47 +0300 
File.read('env') #=> /* content of file */
File.atime('env') #=> 2017-06-24 23:21:47 +0300 
```

**Comment by thomasfl** [comment]
Having no platform specific code or native C code, is what makes filewatcher robust. Maybe this feature could be published as a separate gem that monkeypatches or extends filewatcher?

**Comment by AlexWayfer** [comment]
I'm going on vacation, will return to this topic in 2 weeks :hugs:

**Comment by thomasfl** [comment]
Have a nice vacation @AlexWayfer!

**Comment by thomasfl** [comment]
What do you think about this feature @AlexWayfer? Would you still like to have this feature added to filewatcher? It may be helpful for some linux and osx users. Filewatchers success is probably due to that it "works anywhere and no platform specific code", and this feature will not work anywhere and add platform specific code.

**Comment by AlexWayfer** [comment]
> What do you think about this feature @AlexWayfer? Would you still like to have this feature added to filewatcher? 

I'm planning to implement it as plugin after #71

**Comment by AlexWayfer** [comment]
Done as https://github.com/filewatcher/filewatcher-access
