### ISSUE TITLE
Detect rename

### ISSUE THREAD

**Issue by thomasfl** [filewatcher/filewatcher#99]
For those who need to detect file renaming, it probably is easiest to add a small code example to the README file.

```ruby:
require 'filewatcher'

def getChecksum(filename) do
   ...
end

checksums = {}

Filewatcher.new(['lib/', 'Rakefile']).watch do |filename, event|
    checksums[getChecksum(filename)] = filename
   if event == :add
      oldFilename = checksums[getChecksum(filename)]
      if (oldFilename and notExits?(oldFilename) do
          puts "File renamed from " + oldFilename + " to " + filename
      end
   end
end
```

**Comment by AlexWayfer** [comment]
Why do you think this can be helpful?

I didn't find `rename` request from users. Only #26, and this is about old system (one change, as I remember), and we've added the `--every` option in #53, which allows to detect renames, if needed.

Also, this can be type of event inside Filewatcher (`renamed`), as `modified` or `created`. But I'm still not sure that somebody need this.

**Comment by thomasfl** [comment]
Would it be much work to add a simple code example to the README file that demonstrates how the --every option can be used to from a ruby script to detect file rename?

**Comment by AlexWayfer** [comment]
> Would it be much work to add a simple code example to the README file that demonstrates how the --every option can be used to from a ruby script to detect file rename?

I agree. Done in #100.
